name: SignsListener
author: SiT
main: ru.SignsListener.Main
description: Outputs to log/console labels that players writte on the signs and books.
version: 1.6

commands:
  signslistener:
    description: Main plugin command.
    aliases: [sl]

permissions:
  SignsListener.admin:
  SignsListener.signs.notice:
  SignsListener.books.notice:
  SignsListener.items.notice:
  SignsListener.useFormatting:
  BooksListener.useFormatting: